### PR TITLE
allow utf-8 part values and codes in stickerbom

### PR DESCRIPTION
**Pull request by richardeoin**
useful for greek letters in part values

### CODE REVIEW

**Comment by adamgreig** [comment]
This already worked in Python 3, but sadly in fixing it for Python 2 you've broken it for Python 3 as it now tries to print bytes objects instead of strings (as encode() returns a bytes object).

Not sure what the solution is but I'll check into it further this evening. By the way, could you make sure the lines stay within 79 characters? One of them just needs an extra break.

**Comment by richardeoin** [comment]
I've implemented a dirty manual version check. The real solution might just be to use Python 3..

Line lengths duly noted :)

**Comment by adamgreig** [comment]
I think you can actually just add unicode_literals to the __future__ import at the top and it all works fine in both Pythons, without needing to branch on the different versions

**Comment by richardeoin** [comment]
Yup that works. I was expecting `unicode_literals` to affect the behaviour of string literals and hence ignored it :(

**Comment by adamgreig** [comment]
It does affect the behaviour of string literals - it means the string literal we're calling format() on becomes a unicode object instead of a str object, so when we format it we end up with a unicode object. Same as doing like `show_text(u"bla {} {}".format(a, b))` but neater.

Python eh?

**Comment by adamgreig** [comment]
thank you for the contribution!

**Pull request merged**
