### PR TITLE
Added in power transistors footprints, totem pole NMOS symbol, VSHORE symbol.

### PR DESCRIPTION
**Pull request by Wizongod**
I only did a basic outline on F.Fab for the chip shape (which basically follows the silkscreen). Hope that's ok.

### CODE REVIEW

**Comment by Wizongod** [comment]
Also, most of the transistors don't have a marking for where pin 1 is on the package itself. I think we're just supposed to look at the package underneath and match it to the landing footprint (which is not ambiguous).

**Comment by adamgreig** [comment]
Thanks, these look mostly good. Couple of points.

1. Could you put a brief description and most importantly a link to a datasheet/document in the agg.pretty/README.md file? It would be nice to have a specific datasheet to check the footprint dimensions against and so it's clear in the future what they are meant to fit
2. On the SC75 part, the south courtyard only has 0.20mm clearance
3. On a few footprints the reference and value do not clear the courtyard (but they should)
4. The fab layer needs to have enough on it to orient the chips - usually I have the bottom metallisation at least, and ideally some kind of polarity indicator. I'd be surprised if there was nothing on the chips but if there is any concept of 'pin 1' you could mark that?
5. The silkscreen shouldn't have tiny internal lines - just corners is sufficient, little blobs between pads don't come out well anyway
6. I'm not sure about the package names, specifically SON2x2 - is there a better or more IPC7351B compliant name for the footprint?

**Comment by Wizongod** [comment]
1, 2, 3, 5, all rectified.

\> 4. So I've indicated pin 1 on each of the transistor packages. I'm not sure how useful it'll be though, considering the package itself, for a number of them, don't have a pin 1 indication. Their underside metal is unique enough to not be able to place them wrongly though. I also had to place the pin 1 dot outside in most cases because there was not enough room inside the footprint.

\> 6. I see Farnell calls it the WSON package, so I've updated the name to that. Not sure if that's the better or more compliant name you're looking for. Datasheet here: http://www.farnell.com/datasheets/1969766.pdf
Farnell listing here: http://uk.farnell.com/texas-instruments/csd25310q2/mosfet-p-ch-20v-20a-wson-6/dp/2501102

**Comment by Wizongod** [comment]
Further comment:
> 6. I think the SON name is correct. I'm browsing for another transistor to add on and it seems that TI has several SON packages: SON2x2, SON3x3, and SON3.3x3.3 are the ones I've come across so far. I'll make the correction in the next push along with another transistor I'll be footprinting.

**Comment by Wizongod** [comment]
You know, in some datasheets (e.g. http://www.nxp.com/documents/data_sheet/PCAL9538A.pdf), the recommendation is to put less paste, but still expose the whole pad (and not mask any of it), usually for better thermal conductivity. But so far all of our footprints don't do that. Should we be doing that?

**Pull request merged**
