### PR TITLE
Add Samtec SFM and TFML right-angle connectors

### PR DESCRIPTION
**Pull request by JMW95**
Added footprints for SFM-110-02-L-DH and TFML-110-01-L-D-RA Samtec connectors.

### CODE REVIEW

**Comment by adamgreig** [comment]
Thanks!

For both symbols:
* The outline of the connector should go on F.Fab (along with any internal details you think relevant), not F.CrtYd. Possibly your outline is very slightly (0.02mm off) due to being forced onto a 0.05mm grid for courtyards.
* There should be a courtyard on F.CrtYd, but it should be a rectangle larger than the part itself by the relevant clearance (see the README in agg.pretty for this and other details)
* Should have a drawing on F.SilkS that at least serves to orient (since the part has a "pin 1"), see the autogenerated SFML/TFML for example
* The reference field (REF**) should go on top of the footprint, not on the side (even though this is off the PCB)

For the SFM:
* The PCB edge line should go on F.Fab, not silk screen
* The mounting holes should have large copper pads, at the moment the copper is zero sized so none will be produced and you won't be able to solder the legs in place
* The bottom mounting holes are 1.44mm above the baseline, while the copper pads are the correct 1.35mm above the baseline, and the upper mounting holes are the correct 2.25mm above the lower ones, so the mounting holes are all a bit high by 0.02mm. It's probably not significant...
* Otherwise all the other dimensions seem correct to me!

**Comment by JMW95** [comment]
I've addressed the issues, and fixed the pin numbering on the TFML part.

**Comment by adamgreig** [comment]
Great, thanks.

The copper on the mounting holes for the SFM is still a bit thin - only 0.2mm wide - which will be hard to solder to. Perhaps bulk it up to to 0.4mm wide (so a 1.5mm copper pad with the 0.71mm drill)? There's the same issue on the TFML part - the copper rings here are only 0.1325mm wide which will be very fragile. There's enough clearance to increase this substantially so it would be worth doing.

There's no point having silk on the SFM part that goes beyond the PCB edge - by definition it'l never be printed, so perhaps cut the silkscreen off after the PCB edge line.

Everything else looks good.

**Comment by JMW95** [comment]
I've increased the pad size on the SFM part to 1.5mm as suggested, and increased to 1.1mm on the TFML part - any larger would put the pads too close to each other.

I cut off the silkscreen above the pcb-edge line on the SFM part too, but I left the F.Fab layer intact.

**Comment by adamgreig** [comment]
Great, thank you!

**Pull request merged**
