### PR TITLE
Change stickerbom settings to argparse.

### LINKED ISSUE #61: Swap StickerBOM arguments to command line
Right now StickerBOM parameters (label and page details, and list of suppliers to output) are variables in the file. Better if they file provided defaults that were overridden with command line options using argparse.

### PR DESCRIPTION
**Pull request by HarkonenBade**
Fixes #61.

Will need to be checked over, can't test on my current machine due to pycairo vs windows.

### CODE REVIEW

**Comment by adamgreig** [comment]
Seems to work well but some odd behaviour around `--suppliers`: you have to put this as the very last option, otherwise it sucks up xmlpath and pdfpath too, but the -h suggests you put it first. Perhaps we can make it take one argument and get specified multiple times instead, like `-s Farnell -s Digikey`?

**Comment by HarkonenBade** [comment]
Hmm, I've poked around a bit and come up with some solutions.

Making it action=append does solve that problem, but has the other problem that values then only get appended to the default, so there is no way to remove a supplier from the list.
Other one is that you can stop it glomming arguments by putting either another optional or `--` after it.

Thoughts on the best way forward?

**Comment by adamgreig** [comment]
Could make it a comma separated list that counts as one argument, like `--suppliers Farnell,Digikey,RS`?

**Comment by HarkonenBade** [comment]
Yeah, as I'm guessing that you are not allowed to have comma's in supplier names?

**Comment by adamgreig** [comment]
Probably KiCAD lets you put commas in the field name but... I don't think any suppliers have commas in their names, so...

**Comment by HarkonenBade** [comment]
@adamgreig Happy with this? Or are there any other bits you would like changed first?

**Comment by adamgreig** [comment]
[LGTM](http://lgtm.in/i/cYtYqlh3q)

**Pull request merged**
