### PR TITLE
Add SM{A,B,C} Packages

### PR DESCRIPTION
**Pull request by HarkonenBade**
Adds SMA, SMB and SMC diode packages, based on the package and land
references supplied by Diodes Inc.

### CODE REVIEW

**Comment by HarkonenBade** [comment]
image

**Comment by HarkonenBade** [comment]
image

**Comment by HarkonenBade** [comment]
image

**Comment by HarkonenBade** [comment]
image

**Comment by adamgreig** [comment]
Pads and copper all check out, thanks. Do you think it's worth using the maximum chip width rather than a middle value, so that the courtyard and fab drawing won't be surprisingly too small?

Downside is a huge silk triangle that will stick out on most chips :p

**Comment by HarkonenBade** [comment]
Doesn't really stick out:
image

**Comment by HarkonenBade** [comment]
Does this close #39 ?

**Comment by adamgreig** [comment]
Great, thanks very much. Looks good to me, and yes I think it does close #39.

**Pull request merged**
