### PR TITLE
Reference standard kicad 3d models

### PR DESCRIPTION
**Pull request by HarkonenBade**
Adds standard library kicad 3D models for mod_chip parts.
Partial solution to #58.

### CODE REVIEW

**Comment by HarkonenBade** [comment]
image

**Comment by HarkonenBade** [comment]
image

**Comment by adamgreig** [comment]
looks great! shout when you're done adding models/happy for it to be merged.

**Comment by HarkonenBade** [comment]
image

**Comment by HarkonenBade** [comment]
image

**Comment by HarkonenBade** [comment]
I think I'm done now. I can't see any more easy pickings.

**Comment by adamgreig** [comment]
great work, thanks!

**Pull request merged**
